### ISSUE TITLE
Move Contributing Guide to this Repo and then Improve

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#1]
Other project contributing documents to reference:

- https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md
- https://spack.readthedocs.io/en/latest/contribution_guide.html

**Comment by SteVwonder** [comment]
Also note that this short-how on our website is nice too: http://flux-framework.org/docs/contributing/

**Comment by hauten** [comment]
@SteVwonder what do you want to do about https://github.com/flux-framework/flux-core/blob/master/CONTRIBUTING.md? If it applies to everything, not just core, I can fold it into the new contributing.rst file.

**Comment by hauten** [comment]
To discuss/decide:
- How detailed to get with explaining C4.1? Or just link to those as they are added to the Docs? (example: https://github.com/flux-framework/rfc/blob/master/spec_1.adoc)
- Is there other contrib-related content that will be auto-pulled into Docs?
- What about core's CONTRIBUTING.md, linked above?
- How detailed to get with explaining the workflow that happens with a PR?
- How detailed to get with dev guidelines for new features or other types of contributions someone may make? See MFEM for examples.

**Comment by grondo** [comment]
Just my opinions below:

> How detailed to get with explaining C4.1? Or just link to those as they are added to the Docs? (example: https://github.com/flux-framework/rfc/blob/master/spec_1.adoc)

 - Always link to RFCs. Since the upstream RFC text may change through the same process as code, we wouldn't want any detailed summary to become out-of-date. A synopsis of the basic rules of C4.1 is not a bad idea though.

> What about core's CONTRIBUTING.md, linked above?

 - All framework projects should probably have a `CONTRIBUTING.md` which developers may then reference from a download or checkout copy of the project. Once this docs/CONTRIBUTING guide has a permanent url, then the multiple links in `CONTRIBUTING.md` could be replaced with one that references this doc.

> How detailed to get with explaining the workflow that happens with a PR?

 - IMO, the detail already present is sufficient for new contributors. However we probably do want to make some points explicit, e.g.
     * PRs should be rebased onto the master of the target repo, no merging from master into your branch.
     * PRs that are a work in progress should have WIP: prefix or `work-in-progress` label to avoid automerging by mergify.io.
     * Each commit should have a message with title and body as described in C4.1.

> How detailed to get with dev guidelines for new features or other types of contributions someone may make? See MFEM for examples.

 - I don't think we have rigorous rules about what contributors are allowed to contribute, nor do we specify a huge difference in workflow between new features vs fixes. Perhaps later we can add guidelines to this document as they come up?

**Comment by SteVwonder** [comment]
I second your suggestions, @grondo, with one minor addition:

>> How detailed to get with dev guidelines for new features or other types of contributions someone may make? See MFEM for examples.

> I don't think we have rigorous rules about what contributors are allowed to contribute, nor do we specify a huge difference in workflow between new features vs fixes. Perhaps later we can add guidelines to this document as they come up?

It might be useful to copy some of the sections that MFEM has in their contributing guide.  For example, their [Code Structure Section](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#code-overview), which provides a high-level overview of the repo code structure (modules are here, common utility functions here, libraries here, etc).

---

> Is there other contrib-related content that will be auto-pulled into Docs?

Yeah, the Coding Style Guide ([RFC7](https://github.com/flux-framework/rfc/blob/master/spec_7.adoc)) is important too, but that should be pulled into the docs with the completion of #3.  We will want to link to that.  As a summary of that style guide, we could say something along the lines of:


In general, the components of Flux written in C follow the "Kernighan & Ritchie coding style", with exceptions enumerated in [RFC7](https://github.com/flux-framework/rfc/blob/master/spec_7.adoc).  The components of Flux written in Python follow the [black code style](https://black.readthedocs.io/en/stable/the_black_code_style.html).

**Comment by hauten** [comment]
I'm adding info about the coding style guide (@SteVwonder suggestion) and PR workflow (@grondo suggestion). I opened issue #12 for the Code Structure Section a la MFEM, since a developer will have to write that.

**Comment by hauten** [comment]
Forgot to close this after PR #13 was merged
