### ISSUE TITLE
contributing: bullets/formatting broken

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#104]
There are a few sections in the [contributing page](https://flux-framework.readthedocs.io/en/latest/contributing.html) where there should seemingly be bulleted lists, but there aren't.

<img width="710" alt="Screen Shot 2021-09-22 at 11 21 54 AM" src="https://user-images.githubusercontent.com/874707/134400091-05c8bdfb-a109-4c73-9920-cd4a1599801a.png">

<img width="739" alt="Screen Shot 2021-09-22 at 11 22 01 AM" src="https://user-images.githubusercontent.com/874707/134400049-56246879-aa39-4d11-a9b3-da2e81d7e81d.png">

**Comment by garlick** [comment]
Yeah, just noticed this in the admin guide installation prerequisites.  The following may be relevant:

https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file
