### ISSUE TITLE
quickstart: update `flux module` and `flux job list` usage

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#14]
After the most recent release (i.e., in current master), the flux module command lost the --rank argument, and the flux job list command moved from being a "porcelain" command to being a "plumbing" command. It has been replaced by "flux jobs".

The quickstart.rst should be updated to reflect these changes.

**Comment by cmoussa1** [comment]
This issue should be fixed by PR #20, so I'll go ahead and close this.

**Comment by grondo** [comment]
Note that `flux job list` default output changed again :joy: 

The output can perhaps be updated once we generalize and unify usernames in all examples in the docs.

**Comment by cmoussa1** [comment]
Oops! Thanks for clarifying @grondo 🤣 maybe I should re-open this for now? Do you think those changes could be made in @SteVwonder's current PR?

**Comment by grondo** [comment]
Might as well do it in the fix for #26
