### ISSUE TITLE
quickstart: add `flux keygen` for users running Flux for the first time

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#16]
Without this, a user will get `flux-broker: zsecurity_comms_init: The directory '$HOME/.flux' does not exist.  Have you run "flux keygen"?`

**Comment by vsoch** [comment]
I'm grateful for this issue because I was looking for flux-keygen (per the docs here https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-keygen.html) and I couldn't find it but then I found this issue and found... `flux keygen` ! :raised_hands:

**Comment by garlick** [comment]
`flux keygen` used to be needed if you were going to use Flux at all, but now it's only needed if you are setting up a system instance, e.g.  that bootstraps from systemd.

Quickstart seems to be about PMI-launched Flux (where certs are now generated on the fly and public keys exchanged with PMI) so this can be closed.
