### ISSUE TITLE
use github actions to build with sphinx (and maybe deploy to readthedocs)

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#17]
Relevant github action in the marketplace: https://github.com/marketplace/actions/sphinx-build

**Comment by gonsie** [comment]
Readthedocs does the sphinx build for us, no need for a github action. The action would be if wanted to deploy to someplace else.

**Comment by grondo** [comment]
For PRs, a sphinx build might still be nice just to make sure there are no errors introduced by the PR.

Extra extra credit if the GitHub action could deploy a temporary version of the repo somewhere so reviewers could look at the end result.

**Comment by gonsie** [comment]
Each fork could have a `gh-pages` branch and serve the website via github pages (url would be ghusername.github.io/docs). This action could then deploy the sphinx-built HTML to that branch.

I envision also having a Travis run a make check to make sure that the sphinx build doesn’t return an error, but there would not be a way to see the result (unless individuals set up their own RTD instances)

**Comment by gonsie** [comment]
Oooh! This may be an upcoming feature of RTD: https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html

**Comment by SteVwonder** [comment]
Thanks @gonsie for pointing that out!  That feature has now be enabled for this repo.  It has already started working (automagically).  If you want to see an example, #20 has an accessible build: https://flux-framework--20.org.readthedocs.build/en/20/

**Comment by grondo** [comment]
Wow, that's awsome!

**Comment by SteVwonder** [comment]
I'm going to go ahead and close this issue.  We can re-open if the RTDs feature doesn't meet all of our needs.
