### ISSUE TITLE
Add CORAL-specific documentation from Confluence

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#18]
Need to copy over our Lassen/Sierra specific notes from confluence into here.

Would also serve as a good starting point for Summit-specific docs.

**Comment by jack-morrison** [comment]
Summit-specific end-user docs can live [here](https://docs.olcf.ornl.gov/software/UMS/Flux.html), under `OLCF Docs > Software > User-Managed Software > Flux`.
