### ISSUE TITLE
python api example something not rendering properly

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-docs#207]
Just noticed this when skimming through a build and then noticed it is on the read the docs site.

![image](https://user-images.githubusercontent.com/274859/219098876-c1fa49d5-12b5-41dc-970b-d8108130f3ba.png)

I assume that last chunk should be rendered into something?

**Comment by vsoch** [comment]
That adds the thumbnail for the example - we can probably remove it (I think I since set up the thumbnail to automatically default to the same thing).
