### ISSUE TITLE
Flux-core & Flux-sched as Subprojects?

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#22]
Post-mortem of a recent coffee discussion

Problems:

- How should the submodules for flux-core and flux-sched within flux-docs be updated?
- How should flux-docs be tagged given the loose coupling of the various projects?

Proposed Solution: The rfc repo would remain a submodule because it is not tagged/versions, so we can freely update the submodule reference everytime a PR is merged into rfc's master. flux-core and flux-sched would be [RTD subprojects](https://docs.readthedocs.io/en/stable/subprojects.html) for flux-docs.  So all of the various namespaces and search indexes are shared, but the various projects would still be able to host their own docs that are tagged in the same way that the projects are.  flux-docs would be a parent project that ties everything together, but could now be tagged independently of the other projects.

Open Questions: What is the best way to reference flux-core/flux-sched material from flux-docs?  RTDs subprojects seems to take care of this with the `/projects/<name>` addition to the URL, but does this break sphinx?  Is there any easy way to reference the latest tagged version of a subproject in RTD or RST (or is `latest` as close as we can get)?

I'm sure there a bunch of other questions and details to work out that we haven't thought of yet.

Tagging @gonsie since our discussion last Friday spawn this whole side discussion.

**Comment by SteVwonder** [comment]
Tagging @garlick and @grondo in case I characterised our discussion or left anything out.

**Comment by SteVwonder** [comment]
Did some googling and it looks like [RobotPy](http://www.virtualroadside.com/blog/index.php/2017/01/14/integrated-subproject-sites-on-readthedocs-org/) has a nice readthedocs site with a nice integration of various subprojects.  We could probably emulate them.  One key technology that they reference is the [intersphinx module](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html).

**Comment by gonsie** [comment]
i just added the rfc repo as a readthedocs subproject:  https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/README.html

I’m not sure about how to correctly link between the projects, but eventually I’d like to do something similar to the robotpy project for generating the sidebar.

**Comment by SteVwonder** [comment]
I think the subprojects are well setup at this point.  Thanks @gonsie for all your work in getting that setup.  I think the only remaining action item is the unified sidebar.  I'll open a separate issue for that.
