### ISSUE TITLE
Can Flux be deployed within a job (i.e.: Slurm) in a production cluster?

### ISSUE THREAD

**Issue by siserte** [flux-framework/flux-docs#242]
Hello,

We are planning to port some Slurm custom features to Flux. But first, we'd like to know how to deploy the development environment in our cluster. The cluster does not relies on kubernetes and it is in production with a native Slurm instance for managing the workload. 

Our question is if we can deploy a Flux environment within a Slurm job in the cluster. We usually use this approach using nested Slurm instances where we allocate a set of resources, and then, with the custom Slurm version we deploy the whole insfrastructure within the original job in order to test and evalute new features.

We've checked the documentation and it is not clear about this. Even, it is difficult to understand if Flux can run standalone (no Kubernetes) in a cluster.

Thank you.

**Comment by grondo** [comment]
For development, you can also start a Flux instance standalone with the `flux start` option `-s, --test-size=N`. Much of Flux development was done this way. This command also works from a build directory which allows easy testing of locally developed features:
```console
[grondo@pi3 ~/git/flux-core.git]$ src/cmd/flux start -s 4
[grondo@pi3 ~/git/flux-core.git]$ flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free      4       16        0 pi[3,3,3,3]
 allocated      0        0        0 
      down      0        0        0 
[grondo@pi3 ~/git/flux-core.git]$ flux run -N4 hostname
pi3
pi3
pi3
pi3

```
