### ISSUE TITLE
nix workflow examples readthedocs rendering

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-docs#248]
Problem: While googling for some flux stuff I landed in the deprecated workflow examples [readthedocs pages](https://flux-framework.readthedocs.io/projects/flux-workflow-examples/en/latest/).  Oops.  We set the repo read-only, but maybe we forgot to remove these pages.

**Comment by vsoch** [comment]
I think you can probably turn off that readthedocs build (or delete it) and then ensure any associated links are removed as well.

**Comment by wihobbs** [comment]
Probably should remove [this link to it as well in the Flux Python API docs](https://flux-framework.readthedocs.io/projects/flux-core/en/stable/python/basics.html).

**Comment by garlick** [comment]
I did delete that in the repo and that apparently only updated the "latest" link.   I'm unclear on when "latest" becomes "stable".

https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/basics.html

**Comment by wihobbs** [comment]
Huh, good to know, didn't realize there were two different "branches" in RTD floating around.

**Comment by garlick** [comment]
@vsoch if you have any expert advice here:

How do we go about deleting all the rendered workflow-examples pages?

When does `latest` become `stable` in the project pages?

**Comment by vsoch** [comment]
I think you'd need to poke around readthedocs - e.g., I'm not sure about deleting, but you can hide any version by editing it - here is an example:

![image](https://github.com/flux-framework/flux-docs/assets/814322/ae1f4804-2616-498b-b727-a314cd6830a8)

And I bet for the second question it's something we can control too - e.g., I'd explore under admin:

![image](https://github.com/flux-framework/flux-docs/assets/814322/8ce77705-e2a7-4b62-86f5-d1f6d07d32a5)

I've actually never made a readthedocs site with more than one main version so it's new territory for me too!

**Comment by garlick** [comment]
Thanks!  Sounds like we need someone with admin access on our projects.  Who on the team has that?  My fresh `garlick` readthedocs account is unaffiliated with any projects.

**Comment by vsoch** [comment]
Looks like flux-core has @grondo @gonsie @jameshcorbett and @SteVwonder 

![image](https://github.com/flux-framework/flux-docs/assets/814322/9b8da780-c54d-4221-b051-9b95f4d18837)

And flux-docs is only @cmoussa1

**Comment by garlick** [comment]
Would one of the people listed above kindly crown me an admin on `flux-core`?

**Comment by garlick** [comment]
Oh I guess it's called `flux-workflow-examples` in readthedocs:

https://flux-framework.readthedocs.io/projects/flux-workflow-examples/en/latest/index.html

**Comment by gonsie** [comment]
@garlick What is your readthedocs username? I think it's case sensitive and it's not always your github username.

**Comment by garlick** [comment]
Should be `garlick`.

**Comment by gonsie** [comment]
just added you to flux-framework, flux-core, flux-rfc

**Comment by garlick** [comment]
Thank you @gonsie!  I'm in!  Now I just need  one of the `flux-workflow-examples` owners to do the same for that project.

**Comment by vsoch** [comment]
That repo is grondo, James, and Steven.

**Comment by garlick** [comment]
Project deleted, bwa hah hah.

**Comment by garlick** [comment]
Thanks everybody.
