### ISSUE TITLE
unify all example output under a common username

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-docs#26]
As noted in #25, example output in the quickstart guide uses real usernames, and thus usernames may not match across all examples.

One idea would be to paste all example output from the docker image, in which case I think the username would end up being `flux` (if that's not confusing enough).

**Comment by SteVwonder** [comment]
> One idea would be to paste all example output from the docker image, in which case I think the username would end up being flux (if that's not confusing enough).

I like that idea!  What if we change the username to `flux-user`?

Also, I like your suggestion at coffee time to automate the running of the commands in the docker image so that we don't have to constantly copy and paste from our terminals.

**Comment by grondo** [comment]
> I like that idea! What if we change the username to flux-user?

Weeeellll, `flux-user` is 9 characters and default `flux jobs` output will truncate at 8. (Traditional length of username is 8 characters) However, `fluxuser` works for me, and I didn't mind `user1` either :smile:
