### ISSUE TITLE
Asciidoc Auto-convert Magic

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#3]
Summoning the great and wonderful wizard, @gonsie.

**Comment by garlick** [comment]
When converting man pages, the "stubs" might be easy overlook, so here's a mention (apologies in advance if I'm being captain obvious).

In `flux-core/doc/man3`, we generate `.3` (roff) files from `.adoc` (asciidoc).  In many cases one `.adoc` produces multiple `.3`'s, with content in one, and stubs in the rest.  The stub just contains a troff `.so` (include) of the content in the primary `.3`.  The asciidoc man module produces man pages for every command name listed in the NAME section.  The first is the primary, the rest are stubs.

The stubs just pop out when asciidoc(tor) is run on the `.adoc` file, but we have to list them in the Makefile.am so they get cleaned and installed.  (This is the most brittle aspect of the process).

This commit  illustrates adding stubs to an existing man page: flux-framework/flux-core@01522610f757da3bb18ed48e81174ec25854745a

**Comment by gonsie** [comment]
Thanks @garlick I would have totally missed this feature of adoc stubs. I'll see what rst/sphinx offers.

**Comment by gonsie** [comment]
So it doesn't look like sphinx can natively do the stub thing. We'll have to discuss in some detail what features are needed for man pages building and what we want in the website. Asciidoctor can build HTML from the adoc... so it may be easier to generate the content that way. 😕

**Comment by gonsie** [comment]
I've created a quick test to compare the adoc and rst html and man generation. I think there is a way that we can keep adoc. The discussion will have to be around the format for documenting non-man-page things.

ADOC | RST
------|-----
[adoc file](https://github.com/gonsie/docs-1/blob/gh-pages/test/flux_core_version.adoc) | [rst file](https://github.com/gonsie/docs-1/blob/gh-pages/test/flux_core_version.rst)
[adoc man](https://github.com/gonsie/docs-1/blob/gh-pages/test/flux_core_version.adoc.3) | [rst man](https://github.com/gonsie/docs-1/blob/gh-pages/test/flux_core_version.rst.3)
[adoc rendered html](http://www.gonsie.com/docs-1/test/flux_core_version.adoc.html) | [rst rendered html](http://www.gonsie.com/docs-1/test/flux_core_version.rst.html)

**Comment by SteVwonder** [comment]
Based on some discussion at coffee time, I did some poking around at antora and mkdoc.  It seems like if we don't want to go the sphinx/restructuredtext route, that mkdoc may be the next best option.  Unforunately most of those plugins are alpha-quality projects.  So our mileage may vary there.

My personal vote is to go forward with converting everything to rst and dealing with that fallout, since it seems like the sphinx/rst ecosystem is really strong (with python, c, c++ support ready to go).  But I don't want to speak for the rest of the team.  We should discuss more in our meeting tomorrow.

**Comment by garlick** [comment]
Following up on a bit of discussion we just had:
- I don't think we care if the roff stubbs are really roff stubs or full copies of the text
- we should (continue to) produce roff man pages with a well formed NAME section for scanning tools that build the apropos database (on Ubuntu, stuff in the man-db package)

Example:  idset_create.3 contains the following name section:
```troff
.SH "NAME"
idset_create, idset_destroy, idset_encode, idset_decode, idset_set, idset_clear, idset_first, idset_next, idset_count, idset_equal \- Manipulate numerically sorted sets of non\-negative integers
```
one of the tools that scans these pages is lexgrog(1)
```console
$ lexgrog idset_create.3
idset_create.3: "idset_create - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_destroy - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_encode - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_decode - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_set - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_clear - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_first - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_next - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_count - Manipulate numerically sorted sets of non-negative integers"
idset_create.3: "idset_equal - Manipulate numerically sorted sets of non-negative integers"
```

**Comment by gonsie** [comment]
😭 https://docs.antora.org/antora/2.2/ (a website generator for asciidoc).

But we want the nice python integration. so the conversion is worth it.

**Comment by grondo** [comment]
There, there @gonsie. If it is any consolation we had definitely looked into antora and had decided it wasn't the first approach we should try. :hugs:

**Comment by gonsie** [comment]
Documenting the general conversion process here:

1. remove any `[horizontal]` tags. These are not supported.
2. make sure the top line in the adoc files is not the title. this will generate an error by `asciidoctor`, but it ensures that title line doesn't get gobbled up.
3. make sure any lines beginning with `include::` are escaped (to something like `\include::`)
4. Do the conversion:
```
asciidoctor -b docbook5 -o file.xml file.adoc
pandoc --base-header-level=1 --wrap=preserve -f docbook -o file.rst file.xml
sed -i '' 's@.xml@.rst@g' file.rst
sed -i '' 's@   \*\*Note\*\*@.. note:: @g' file.rst
sed -i '' 's@   include::@.. literalinclude:: @g' file.rst
sed -i '' 's@yaml\[\]@yaml@g' file.rst
sed -i '' 's@json\[\]@JSON@g' file.rst
sed -i '' '/.. __/d' file.rst
```
5. fix up links between the doc files. should be formatted as: 
```
:doc:`Link text <filename>`
```
6. fix up footnote links. should be formatted inline as: `[#f1]__` and at the bottom of the file with: `.. [#f1]`
7. fix up the language specification of included files (not sure adding a language is 100% necessary if the file extension can be properly parsed). The resulting diff should look like:
```
- .. code:: json
- 
   .. literalinclude:: data/file.json
+    :language: json
+ 
```
7. fix up table whitespace. 
8. add new rst file to `index.rst`
9. ensure that `make html` for the sphinx project works correctly.

**Comment by SteVwonder** [comment]
I think this issue has been taken care of.  Thanks @gonsie! Closing.
