### ISSUE TITLE
Create an FAQ page

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#33]
Good questions to bootstrap the page:

- Why is Flux not discovering and managing all of the resources on the system/node?
	- Various bind flags passed to the parallel launcher that started Flux
	- CUDA enabled hwloc (for GPUs)
- How do I efficiently launch a large number of jobs to Flux?
	- Pointer to our bulksubmit workflow example and flux-tree
- Memory exhaustion on a node when running large ensembles with Flux
	- Set `rundir` so that the content store is not saved to `/tmp` but to a filesystem
- Bring Your Own Python (BYOP)
	- Caveats on what will work and what won't when using a version of python that isn't the one Flux was configured against
- How do I mimic Slurm's jobstep semantics (could later be moved to a "Flux vs Slurm" or "Porting from Slurm" page)
    - `flux mini submit`ting a script with `flux mini run`s will not result in Slurm-style jobsteps unless you stick `flux start` in from of the jobscript in `flux mini submit`
- Flux fails to bootstrap a specific MPI implemention (e.g., OpenMPI, MPICH, Spectrum MPI):
	- Use the `-o mpi=` option when running/submitting jobs
- Does Flux run on a mac?
	- Not yet.  We have an open issue on GitHub tracking the progress towards the goal of natively compiling on a mac.  In the meantime, you can use Docker (pointer to our docker install instructions).
- How do I report a bug or ask a question not answered here?
	- Either a pointer to the GitHub issue tracker, or a pointer to a docs page that outlines how to get help
- How do I request a resource for scheduling not listed as an argument to `flux mini` (e.g., `memory` or `storage`)?
	- Once `flux run` is merged, we can point to that documentation

**Comment by SteVwonder** [comment]
- For module/service writers
  - My message callback is not being run.  How do I debug?
	- Check the error codes from addvec, register_service, the RPC, etc
    - Use FLUX_O_TRACE and FLUX_HANDLE_TRACE to see messages moving through the overlay

**Comment by SteVwonder** [comment]
- I'm experiencing a hang while running my parallel application.  How can I debug?
  - Run `flux mini run/submit` with the `-vvv` argument
  - If it is hanging in startup, try adding the PMI DEBUG env var
  - Anything else?

**Comment by grondo** [comment]
Might want to add instructions to attach with parallel debugger (if the job has reached `shell.start`)

**Comment by SteVwonder** [comment]
### How does the versioning of Flux and it's various poly-repos work?

(Rough text from a slack message response below, should be tweaked and cleaned up before it lands in the docs)

For any given repo, the versioning is typical semantic versioning.  We are still < 1.0, so all of our interfaces are subject to change and break.  Once we hit 1.0, they will only change on major version increments.  New features get added in minor releases. Etc

The brain-bending part of the versioning comes from the poly-repo structure.  Flux-sched is it's own repo with it's own versioning scheme.  A release on flux-core may not break anything in flux-sched or require chaanges and thus might not warrant a new release.   So the flux-core and flux-sched versions do not get incremented in lockstep.  Already, flux-core is on 0.16.0 and flux-sched is on 0.8.0.   We have the compatibility of the various flux-core/flux-sched versions codified in our spack packages, but that will get more extensive as we add additional repos like flux-depend and flux-accounting.  (TODO: we should make a table and put it in the docs too)

We recently discussed adding a 'flux' meta-package to spack (and to other distro package managers) that would pull in compatible versions of the various sub-packages/repos.   We haven't worked out all the details yet, but I don't think the versioning of that meta-package will have any connection to any of the sub-packages.

Similar thing for the flux-docs repo and the documentation up on readthedocs.  Each repo has it's own documentation and that gets tagged and released along with the code, but the high-level "meta" documentation has it's own versioning that is divorced from any particular sub-packages/repos versioning.
