### ISSUE TITLE
Spell check does not appear to run as part of the CI

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#43]
Caught several spelling mistakes in a recent PR despite the CI returning all green.  We probably need to add an explicit github action that runs `make check`.

**Comment by gonsie** [comment]
This is really a couple of issues:

1. Spell-check is not included in the flux-docs repo (yet)
2. Spell-check doesn’t seem to be happening in rfc repo. (Really, it is happening, but misspellings create a warning, not an error and thus PRs are not marked as failing).

I’ll get on it.

**Comment by SteVwonder** [comment]
Thanks @gonsie for breaking this down and fixing the issues with the RFC repo!  To help @garrettbslone with his current PR, I'm copying over the spell-check functionality from RFC into flux-docs now.  I should have a PR up shortly.
