### ISSUE TITLE
flux system administration guide

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-docs#58]
I think we'll need a guide for system administrators when flux is deployed as the system resource manager.   We were talking about getting some feedback from sys admins on our current set of tools.  Perhaps an admin guide would help with that, and could document known shortcomings in our early releases.

A straw man outline to start the discussion:

* Configuration
  - Installing flux packages
  - Security: setuid IMP, flux user, MUNGE, Curve keys
  - Overlay: selecting a network, TBON topology
  - Resource: hwloc, config via R TBD
  - Storage: content backing store, logs, job archive
* Day to day administration
  - Changing the Flux configuration
  - Updating Flux software
  - Draining nodes
  - Stopping the flux queue
  - Expediting jobs
  - Canceling jobs
  - Dedicated Application Time
* Troubleshooting
  - Logs: systemd journal, flux dmesg, KVS eventlogs
  - What happened to a job?
  - What happened to the system?
  - What happened to a node/resource?
  - Queue order?
  - Anticipated/common failure modes TBD

**Comment by dongahn** [comment]
From our meeting with Ryan and etc:

•	Mark and Jim to develop the system admin guide by 9/10/2020 and send it to Ryan to get the feedback from his team

**Comment by grondo** [comment]
#63 merged so closing !
