### ISSUE TITLE
Admin Guide: syntax highlighting in TOML examples

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#64]
It looks like the admin guide uses TOML code blocks in the ReST code, and the syntax highlighting of those blocks works on GitHub but not on ReadTheDocs.  Not sure if this reproduces locally, but it happens on the hosted RTD site.

GitHub Screenshot:
<img width="241" alt="Screen Shot 2020-09-16 at 12 38 44 PM" src="https://user-images.githubusercontent.com/874707/93384402-a12a5b80-f819-11ea-92bc-018f392ab556.png">

RTD Screenshot:
<img width="243" alt="Screen Shot 2020-09-16 at 12 38 52 PM" src="https://user-images.githubusercontent.com/874707/93384418-a8ea0000-f819-11ea-82e1-85e4769ccdb9.png">

**Comment by SteVwonder** [comment]
It seems to work just fine locally, so maybe it is a versioning or dependency issue with the hosted version that RTD is running:

<img width="244" alt="Screen Shot 2020-09-16 at 12 48 09 PM" src="https://user-images.githubusercontent.com/874707/93385419-1b0f1480-f81b-11ea-8670-21549c3cd176.png">

Locally I'm running Sphinx v3.2.1.

**Comment by grondo** [comment]
Yeah, worked locally for me as well. (Sphinx 3.1.2)

**Comment by SteVwonder** [comment]
After recreating the virtualenv that RTD uses on my local machine, it looks to be due to an older version of Pygments:

```
Running Sphinx v1.8.5
Initializing Spelling Checker
loading pickled environment... failed: unsupported pickle protocol: 5
loading intersphinx inventory from https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/objects.inv...
loading intersphinx inventory from https://flux-framework.readthedocs.io/projects/flux-core/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: 8 added, 0 changed, 0 removed
reading sources... [100%] quickstart
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] quickstart
/Users/herbein1/Repositories/flux-framework/flux-docs/adminguide.rst:139: WARNING: Pygments lexer name u'toml' is not known
/Users/herbein1/Repositories/flux-framework/flux-docs/adminguide.rst:150: WARNING: Pygments lexer name u'toml' is not known
/Users/herbein1/Repositories/flux-framework/flux-docs/adminguide.rst:169: WARNING: Pygments lexer name u'toml' is not known
/Users/herbein1/Repositories/flux-framework/flux-docs/adminguide.rst:184: WARNING: Pygments lexer name u'toml' is not known
/Users/herbein1/Repositories/flux-framework/flux-docs/adminguide.rst:207: WARNING: Pygments lexer name u'toml' is not known
/Users/herbein1/Repositories/flux-framework/flux-docs/adminguide.rst:244: WARNING: Pygments lexer name u'toml' is not known
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 6 warnings.
```

If we bump the python version in the [RTD config file](https://docs.readthedocs.io/en/stable/config-file/v2.html), then we will be able to pull in a newer version of Pygments for the hosted build.  I'll give that a shot with a quick PR now.

**Comment by grondo** [comment]
Nice! Thanks for looking into this (I would have had no idea where to start)

**Comment by SteVwonder** [comment]
Np!  After doing all that local reproduction, I realized you can just click on individual commands run within the RTD build and the output gets expanded out, like in Travis (but not as obvious a UI as Travis): https://readthedocs.org/projects/flux-framework/builds/11897212/
