### ISSUE TITLE
Using `flux-proxy` on a machine with launch nodes

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-docs#70]
For Summit (and Lassen, depending on if you use lalloc or not), the default behavior is to allocate compute nodes and a launch node for every job.  The batch script is then run on the launch node and any use of the system parallel launcher `jsrun` to execute Flux results in all of the Flux processes to land on the compute nodes and none on the launch node.  If a user captures the `local://` FLUX URI and tries to use that from the launch node, it will fail, since the Unix socket is on the compute nodes not the launch node.  This behavior is different from typical clusters where launch nodes are not used.

**Comment by SteVwonder** [comment]
One potential solution is to use to construct and use an `ssh://` FLUX URI to leverage the ssh connector rather than the local connector.  This will create an ssh connection between the launch node and the compute node on which Flux is running.

**Comment by garlick** [comment]
That should be doable, provided you can somehow capture FLUX_URI from one of the brokers and transform it.   Alternate idea would be to set the `local-uri` attribute on the broker command line to something you know in advance, but careful - if command line applies to all brokers, it has to work for all.

Does jsrun have options by chance to include the launch node in the "job"?  If you could locate flux rank 0 on the launch node, and then exclude it from scheduling, that would be sorta convenient.  The initial program / shell would then run on the launch node and the system's model would be preserved.

How do we usually run on this system?

**Comment by SteVwonder** [comment]
> Does jsrun have options by chance to include the launch node in the "job"? 

That's a good question. I'm not sure, but I think not.  I don't see one documented in [LLNL](https://hpc.llnl.gov/banks-jobs/running-jobs/slurm-srun-versus-ibm-csm-jsrun) or [ORNL's docs](https://docs.olcf.ornl.gov/systems/summit_user_guide.html#node-types).  I did see this in the ORNL ones though:

> All commands within your job script (or the commands you run in an interactive job) will run on a launch node. Like login nodes, these are shared resources so you should not run multiprocessor/threaded programs on Launch nodes.

If there is a way, I suspect running rank 0 of a large Flux instance on the Launch node would be frowned upon due to all the activity the KVS and other rank 0 modules generates.

> How do we usually run on this system?

At LLNL, we typically use `lrun` (and its variants) which by default runs your job script on a compute node, so this particular issue isn't common on LLNL systems.  ORNL does not have a similar wrapper script or setup.

>  Alternate idea would be to set the local-uri attribute on the broker command line to something you know in advance, but careful - if command line applies to all brokers, it has to work for all.

That's a really good idea.  Pointing the local-uri or even the whole rundir to GPFS or some other global filesystem would solve this issue, right? (Actually, now that I think about it, do Unix sockets work over Lustre/GPFS???)   I wonder if jsrun has an MPMD mode that would make giving rank 0 a local-uri argument easy.  If not, I wonder if that is something we should consider adding directly to `flux start`.

**Comment by garlick** [comment]
I'm not sure if this is what you meant, but UNIX domain sockets just use the file system namespace to identify an endpoint in the local kernel.  You can't bind to a socket path pointing into a network file system on one node and connect to it on another node, unfortunately.

I just meant that it might be easier to force the path to the local socket to something you know, than to let the broker choose something random and then have to ascertain what it chose.

**Comment by grondo** [comment]
A uri including the jobid might make sense here, if the jobid is available
in the batch script environment.
